dji_gimbal:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Position Controllers ---------------------------------------
  yaw_position_controller:
    type: effort_controllers/JointPositionController
    joint: yaw
    pid: {p: 1, i: 0.01, d: 0.001}
  pitch_position_controller:
    type: effort_controllers/JointPositionController
    joint: pitch
    pid: {p: 1, i: 0.01, d: 0.001}
  roll_position_controller:
    type: effort_controllers/JointPositionController
    joint: roll
    pid: {p: 1, i: 0.01, d: 0.001}